//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class ___VARIABLE_viewName___View: UIView {
    //MARK: - Propriedades
    //MARK: - Construtores
    override init(frame: CGRect) {
        super.init(frame: frame)
        setup()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

//MARK: - Fluxo de Montagem da cena
extension ___VARIABLE_viewName___View{
    func setup(){
        setupSubviews()
        setupLayout()
        setupStyle()
    }
    
    func setupSubviews(){}
    func setupLayout(){}
    func setupStyle(){}
}

//MARK: - Miscelanea
extension ___VARIABLE_viewName___View{
    
}
